name: Prepare Docker env variables
description: 'Prepare env variables'
outputs:
  DATE_YEAR_WEEKNUM:
    description: "DATE_YEAR_WEEKNUM"
    value: ${{ steps.prepare-env-variables.outputs.DATE_YEAR_WEEKNUM }}
  BUILD_DATE:
    description: "BUILD_DATE"
    value: ${{ steps.prepare-env-variables.outputs.BUILD_DATE }}
  BUILD_FINGERPRINT:
    description: "BUILD_FINGERPRINT"
    value: ${{ steps.prepare-env-variables.outputs.BUILD_FINGERPRINT }}
  BRANCH_NAME:
    description: "BRANCH_NAME"
    value: ${{ steps.prepare-env-variables.outputs.BRANCH_NAME }}
runs:
  using: "composite"
  steps:
    - id: prepare-env-variables
      shell: bash
      run: |
        echo "DATE_YEAR_WEEKNUM=$(TZ=':UTC' date +'%Y-%U')" >> ${GITHUB_OUTPUT}
        echo "BUILD_DATE=$(TZ=':UTC' date +'%Y-%m-%d %H:%M:%S (%Z)')" >> ${GITHUB_OUTPUT}
        echo "BUILD_FINGERPRINT=${GITHUB_SHA::7}" >> ${GITHUB_OUTPUT}
        echo "BRANCH_NAME=${{ github.head_ref || github.ref_name }}" >> ${GITHUB_OUTPUT}
