# Alexander Tebiev - https://github.com/beeyev
name: PHPStan check

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
    paths:
      - "**.php"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  phpstan-check:
    name: PHPStan check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.draft == false
    permissions:
      contents: write
      pull-requests: write
    env:
      PHP-VERSION: '8.0'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Prepare PHP Environment
        uses: ./.github/actions/prepare-php-environment/
        with:
          php-version: ${{ env.PHP-VERSION }}

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1

      - name: Cache PHPStan results
        uses: actions/cache@v3
        with:
          path: ${{ steps.phpstan-install.outputs.PHPSTAN_CACHE_DIR }}
          key: phpstan-cache-dir-${{ github.workflow }}

      - name: Run PHPStan Check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          XDEBUG_MODE=off php vendor/bin/phpstan analyse --configuration=phpstan.neon.dist --error-format=raw --no-progress --memory-limit=1G | reviewdog -reporter=github-check -f=phpstan -level=error -filter-mode=nofilter -tee
