name: PHPUnit tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
    paths:
      - "**.php"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  phpunit-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.0', '7.2', '7.4', '8.0', '8.2']
    name: PHPUnit Tests / PHP ${{ matrix.php-version }}
    timeout-minutes: 15
    if: github.event.pull_request.draft == false
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Prepare PHP Environment
        uses: ./.github/actions/prepare-php-environment/
        with:
          php-version: ${{ matrix.php-version }}

      - name: PHPUnit Tests
        run: |
          vendor/bin/phpunit
