name: Code Style

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master, develop]
    paths:
      - "**.php"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-22.04
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

  pr-check:
    name: PR Check
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: |
            /tmp/composer-cache/
            vendor/
          key: ${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.0
          version: 2.2.x
          dev: no

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          version: 7
          php_version: 7.0
          configuration: phpunit.xml.dist
          bootstrap: vendor/autoload.php

#      - uses: ./.github/actions/prepare-env-variables/
#        id: prepare-build-env-variables
#        with:
#          php-version: 7.0
#
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
