name: PHPUnit tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
    paths:
      - "**.php"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  phpunit-tests:
    runs-on: ubuntu-22.04
    name: PHP phpunit
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-env-variables/
        id: prepare-build-env-variables
        with:
          php-version: '7.0'
