name: Tests

# Controls when the workflow will run
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Unit Tests for PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.stability }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 10
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.4', '8.0', '8.1' ]
        stability: [ prefer-lowest, prefer-stable ]

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: opcache
          ini-values: disable_functions, error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: ./vendor/bin/pest
